# Site settings
title: huailei blog
SEOTitle: 怀雷 | huailei Blog
header-img: img/home-bg-o.jpg
email: huailei2017@gmail.com
description: "Trust The Process"
keyword: "Trust The Process"
url:               # your host, for absolute URL
baseurl:          # for example, '/blog' if your blog hosted on 'host/blog'

future: true


# SNS settings
RSS: false
zhihu_username:     huai-lei-18
github_username:    huaileicoder
twitter_username:  	
#facebook_username:  huaileicoder



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: 
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: a4f7e46b75646ed0826065e1712928a8
# Google Analytics
ga_track_id: UA-124573520-1            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Trust The Process"
sidebar-avatar: /img/avatar-huai.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


#gitment
comment_gitment_repo: huaileicoder
comment_gitment_clientId: 397e0b72052c93816d18
comment_gitment_clientSecret: 666a12fc008ea8e25c1992f8e810c3d485073e7a



# Friends
friends: [
 
]
